### ISSUE TITLE
Model Gardens Support - Claude 3.5 Sonnet via Vertex AI or Bedrock 

### ISSUE THREAD

**Issue by davideconsonni** [devoxx/DevoxxGenieIDEAPlugin#250]
Hi, would it be possible to use the models contained within Google Vertex AI or AWS Bedrock?

Ciao
Davide

**Comment by stephanj** [comment]
Yes, DevoxxGenie already supports Google Gemini using the REST interface instead of using Google Vertex AI API which requires project & location ID and service account (or something similar).

DevoxxGenie uses LangChain4J as the underlying framework to access the local and cloud models.
This framwork does support both [Google Vertex AI](https://docs.langchain4j.dev/integrations/language-models/google-gemini/) and [AWS Bedrock](https://docs.langchain4j.dev/integrations/language-models/amazon-bedrock/).  As mentioned above, the "challenge" is the authentication process becayse they don't use a simple api key.

**Comment by rxliuli** [comment]
> Hi, would it be possible to use the models contained within Google Vertex AI or AWS Bedrock?
> 
> Ciao Davide

You might be interested in an open-source proxy tool I recently wrote called OpenAI API Proxy. It converts the APIs of many models into OpenAI-compatible interfaces, including Google Vertex AI. This allows me to use Claude 3.5 Sonnet via Vertex AI on tools that don't support Vertex AI models. It can be deployed for free on any Edge Runtime platform, such as Cloudflare Workers.

https://github.com/rxliuli/openai-api-proxy
